---
title: "DOI extraction and matching"
output: github_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE
)
```


```{r}
library(tidyverse)
library(stringi)
library(biblids) # https://github.com/subugoe/biblids
```

```{r}
npl_df <- readr::read_csv("data/bq_doi_20210824.csv")
```

extract dois

```{r}
npl_tt <- npl_df %>% 
  mutate(doi = biblids::str_extract_all_doi(npl_text)) %>%
  select(doi, publication_number)

npl_tidy <- tibble(
  as.data.frame(npl_tt$doi),
  publication_number = npl_tt$publication_number) %>%
  pivot_longer(!publication_number) %>%
  filter(!is.na(value)) %>%
  select(-name) %>%
  mutate(doi_cleaned = str_remove(value, "\\.$")) %>%
  mutate(doi_cleaned = str_remove(doi_cleaned, "\\>$")) %>%
  mutate(doi_cleaned = str_remove(doi_cleaned, "\\,$")) %>%
  mutate(doi_cleaned = str_remove(doi_cleaned, "\\;$")) %>%
  select(-value)

npl_tidy

npl_tidy %>%
  write_csv("data/dois_to_be_checked.csv")
```

Upload to Google Big Query 

```{r}
library(bigrquery)

patent_dois <- 
  bq_table("api-project-764811344545", "tmp", "patent_dois")
if(bq_table_exists(patent_dois)) 
  bq_table_delete(patent_dois)
bigrquery::bq_table_upload(
  patent_dois,
  npl_tidy)
```


